# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EventsApi")

api.instance <- EventsApi$new()

test_that("EventsGet", {
  # tests for EventsGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the Events
  # Get list of events
  # @param study.db.id character Filter based on study unique identifier in which the events occurred (optional)
  # @param observation.unit.db.id character Filter based on an ObservationUnit unique identifier in which the events occurred (optional)
  # @param event.db.id character Filter based on an Event DbId (optional)
  # @param event.type character Filter based on an Event Type (optional)
  # @param date.range.start character Filter based on an Date Range (optional)
  # @param date.range.end character Filter based on an Date Range (optional)
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [EventsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

