# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test LinkageGroup")

model.instance <- LinkageGroup$new()

test_that("additionalInfo", {
  # tests for the property `additionalInfo` (map(character))
  # Additional arbitrary info

  # uncomment below to test the property 
  #expect_equal(model.instance$`additionalInfo`, "EXPECTED_RESULT")
})

test_that("linkageGroupName", {
  # tests for the property `linkageGroupName` (character)
  # The Uniquely Identifiable name of this linkage group

  # uncomment below to test the property 
  #expect_equal(model.instance$`linkageGroupName`, "EXPECTED_RESULT")
})

test_that("markerCount", {
  # tests for the property `markerCount` (integer)
  # The number of markers associated with this linkage group

  # uncomment below to test the property 
  #expect_equal(model.instance$`markerCount`, "EXPECTED_RESULT")
})

test_that("maxPosition", {
  # tests for the property `maxPosition` (integer)
  # The maximum position of a marker within this linkage group

  # uncomment below to test the property 
  #expect_equal(model.instance$`maxPosition`, "EXPECTED_RESULT")
})

