# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CrossParent")

model.instance <- CrossParent$new()

test_that("germplasmDbId", {
  # tests for the property `germplasmDbId` (character)
  # the unique identifier for a germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`germplasmDbId`, "EXPECTED_RESULT")
})

test_that("germplasmName", {
  # tests for the property `germplasmName` (character)
  # the human readable name for a germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`germplasmName`, "EXPECTED_RESULT")
})

test_that("observationUnitDbId", {
  # tests for the property `observationUnitDbId` (character)
  # the unique identifier for an observation unit

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationUnitDbId`, "EXPECTED_RESULT")
})

test_that("observationUnitName", {
  # tests for the property `observationUnitName` (character)
  # the human readable name for an observation unit

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationUnitName`, "EXPECTED_RESULT")
})

test_that("parentType", {
  # tests for the property `parentType` (character)
  # The type of parent ex. &#39;MALE&#39;, &#39;FEMALE&#39;, &#39;SELF&#39;, &#39;POPULATION&#39;, etc.

  # uncomment below to test the property 
  #expect_equal(model.instance$`parentType`, "EXPECTED_RESULT")
})

