# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SeedLotNewTransactionRequest")

model.instance <- SeedLotNewTransactionRequest$new()

test_that("additionalInfo", {
  # tests for the property `additionalInfo` (map(character))
  # Additional arbitrary info

  # uncomment below to test the property 
  #expect_equal(model.instance$`additionalInfo`, "EXPECTED_RESULT")
})

test_that("amount", {
  # tests for the property `amount` (numeric)
  # The amount of units being transfered. Could be a count (seeds, bulbs, etc) or a weight (kg of seed).

  # uncomment below to test the property 
  #expect_equal(model.instance$`amount`, "EXPECTED_RESULT")
})

test_that("externalReferences", {
  # tests for the property `externalReferences` (array[object])
  # An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.

  # uncomment below to test the property 
  #expect_equal(model.instance$`externalReferences`, "EXPECTED_RESULT")
})

test_that("fromSeedLotDbId", {
  # tests for the property `fromSeedLotDbId` (character)
  # The identifier for the Seed Lot being transfered out of

  # uncomment below to test the property 
  #expect_equal(model.instance$`fromSeedLotDbId`, "EXPECTED_RESULT")
})

test_that("toSeedLotDbId", {
  # tests for the property `toSeedLotDbId` (character)
  # The identifier for the Seed Lot being transfered into

  # uncomment below to test the property 
  #expect_equal(model.instance$`toSeedLotDbId`, "EXPECTED_RESULT")
})

test_that("transactionDescription", {
  # tests for the property `transactionDescription` (character)
  # A general description of this Seed Lot Transaction

  # uncomment below to test the property 
  #expect_equal(model.instance$`transactionDescription`, "EXPECTED_RESULT")
})

test_that("transactionTimestamp", {
  # tests for the property `transactionTimestamp` (character)
  # The time stamp for when the transaction occurred

  # uncomment below to test the property 
  #expect_equal(model.instance$`transactionTimestamp`, "EXPECTED_RESULT")
})

test_that("units", {
  # tests for the property `units` (character)
  # Description of the things being transfered in this transaction (seeds, bulbs, kg, etc)

  # uncomment below to test the property 
  #expect_equal(model.instance$`units`, "EXPECTED_RESULT")
})

