# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProgenyNode")

model.instance <- ProgenyNode$new()

test_that("germplasmDbId", {
  # tests for the property `germplasmDbId` (character)
  # The ID which uniquely identifies a germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`germplasmDbId`, "EXPECTED_RESULT")
})

test_that("germplasmName", {
  # tests for the property `germplasmName` (character)
  # A human readable name for a germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`germplasmName`, "EXPECTED_RESULT")
})

test_that("progeny", {
  # tests for the property `progeny` (array[ProgenyNodeProgeny])
  # List of germplasm entities which are direct children of this germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`progeny`, "EXPECTED_RESULT")
})

