# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VendorOrderSubmission")

model.instance <- VendorOrderSubmission$new()

test_that("orderId", {
  # tests for the property `orderId` (character)
  # A unique, alpha-numeric ID which identifies the order

  # uncomment below to test the property 
  #expect_equal(model.instance$`orderId`, "EXPECTED_RESULT")
})

test_that("shipmentForms", {
  # tests for the property `shipmentForms` (array[ShipmentForm])
  # Array of paper forms which need to be printed and included with the physical shipment

  # uncomment below to test the property 
  #expect_equal(model.instance$`shipmentForms`, "EXPECTED_RESULT")
})

