# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VendorOrder")

model.instance <- VendorOrder$new()

test_that("clientId", {
  # tests for the property `clientId` (character)
  # A unique, alpha-numeric ID which identifies the client to the vendor. Used to connect the order to the correct billing and contact info.

  # uncomment below to test the property 
  #expect_equal(model.instance$`clientId`, "EXPECTED_RESULT")
})

test_that("numberOfSamples", {
  # tests for the property `numberOfSamples` (integer)
  # The total number of samples contained in this request. Used for billing and basic validation of the request.

  # uncomment below to test the property 
  #expect_equal(model.instance$`numberOfSamples`, "EXPECTED_RESULT")
})

test_that("orderId", {
  # tests for the property `orderId` (character)
  # The order id returned by the vendor when the order was successfully submitted.

  # uncomment below to test the property 
  #expect_equal(model.instance$`orderId`, "EXPECTED_RESULT")
})

test_that("requiredServiceInfo", {
  # tests for the property `requiredServiceInfo` (map(character))
  # A map of additional data required by the requested service. This includes things like Volume and Concentration.

  # uncomment below to test the property 
  #expect_equal(model.instance$`requiredServiceInfo`, "EXPECTED_RESULT")
})

test_that("serviceIds", {
  # tests for the property `serviceIds` (array[character])
  # A list of unique, alpha-numeric ID which identify the requested services to be applied to this order.  A Vendor Service defines what platform, technology, and markers will be used.  A list of available service IDs can be retrieved from the Vendor Specs.

  # uncomment below to test the property 
  #expect_equal(model.instance$`serviceIds`, "EXPECTED_RESULT")
})

