# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OntologiesApi")

api.instance <- OntologiesApi$new()

test_that("OntologiesGet", {
  # tests for OntologiesGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the Ontologies
  # Call to retrieve a list of observation variable ontologies available in the system.
  # @param ontology.db.id character The unique identifier for an ontology definition (optional)
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [OntologyListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

