# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ObservationSearchRequestAllOf")

model.instance <- ObservationSearchRequestAllOf$new()

test_that("observationDbIds", {
  # tests for the property `observationDbIds` (array[character])
  # The unique id of an Observation

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationDbIds`, "EXPECTED_RESULT")
})

test_that("observationLevelRelationships", {
  # tests for the property `observationLevelRelationships` (array[ObservationUnitLevelRelationship])
  # Searches for values in ObservationUnit-&gt;observationUnitPosition-&gt;observationLevelRelationships

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationLevelRelationships`, "EXPECTED_RESULT")
})

test_that("observationLevels", {
  # tests for the property `observationLevels` (array[ObservationUnitLevelRelationship])
  # Searches for values in ObservationUnit-&gt;observationUnitPosition-&gt;observationLevel

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationLevels`, "EXPECTED_RESULT")
})

test_that("observationTimeStampRangeEnd", {
  # tests for the property `observationTimeStampRangeEnd` (character)
  # Timestamp range end

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationTimeStampRangeEnd`, "EXPECTED_RESULT")
})

test_that("observationTimeStampRangeStart", {
  # tests for the property `observationTimeStampRangeStart` (character)
  # Timestamp range start

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationTimeStampRangeStart`, "EXPECTED_RESULT")
})

test_that("observationUnitDbIds", {
  # tests for the property `observationUnitDbIds` (array[character])
  # The unique id of an Observation Unit

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationUnitDbIds`, "EXPECTED_RESULT")
})

test_that("seasonDbIds", {
  # tests for the property `seasonDbIds` (array[character])
  # The year or Phenotyping campaign of a multi-annual study (trees, grape, ...)

  # uncomment below to test the property 
  #expect_equal(model.instance$`seasonDbIds`, "EXPECTED_RESULT")
})

