# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProgramSearchRequest")

model.instance <- ProgramSearchRequest$new()

test_that("page", {
  # tests for the property `page` (integer)
  # Which result page is requested. The page indexing starts at 0 (the first page is &#39;page&#39;&#x3D; 0). Default is &#x60;0&#x60;.

  # uncomment below to test the property 
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

test_that("pageSize", {
  # tests for the property `pageSize` (integer)
  # The size of the pages to be returned. Default is &#x60;1000&#x60;.

  # uncomment below to test the property 
  #expect_equal(model.instance$`pageSize`, "EXPECTED_RESULT")
})

test_that("commonCropNames", {
  # tests for the property `commonCropNames` (array[character])
  # Common name for the crop which this program is for

  # uncomment below to test the property 
  #expect_equal(model.instance$`commonCropNames`, "EXPECTED_RESULT")
})

test_that("programDbIds", {
  # tests for the property `programDbIds` (array[character])
  # A program identifier to search for

  # uncomment below to test the property 
  #expect_equal(model.instance$`programDbIds`, "EXPECTED_RESULT")
})

test_that("programNames", {
  # tests for the property `programNames` (array[character])
  # A name of a program to search for

  # uncomment below to test the property 
  #expect_equal(model.instance$`programNames`, "EXPECTED_RESULT")
})

test_that("externalReferenceIDs", {
  # tests for the property `externalReferenceIDs` (array[character])
  # List of external reference IDs. Could be a simple strings or a URIs. (use with &#x60;externalReferenceSources&#x60; parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`externalReferenceIDs`, "EXPECTED_RESULT")
})

test_that("externalReferenceSources", {
  # tests for the property `externalReferenceSources` (array[character])
  # List of identifiers for the source system or database of an external reference (use with &#x60;externalReferenceIDs&#x60; parameter)

  # uncomment below to test the property 
  #expect_equal(model.instance$`externalReferenceSources`, "EXPECTED_RESULT")
})

test_that("abbreviations", {
  # tests for the property `abbreviations` (array[character])
  # An abbreviation of a program to search for

  # uncomment below to test the property 
  #expect_equal(model.instance$`abbreviations`, "EXPECTED_RESULT")
})

test_that("leadPersonDbIds", {
  # tests for the property `leadPersonDbIds` (array[character])
  # The person DbIds of the program leader to search for

  # uncomment below to test the property 
  #expect_equal(model.instance$`leadPersonDbIds`, "EXPECTED_RESULT")
})

test_that("leadPersonNames", {
  # tests for the property `leadPersonNames` (array[character])
  # The names of the program leader to search for

  # uncomment below to test the property 
  #expect_equal(model.instance$`leadPersonNames`, "EXPECTED_RESULT")
})

test_that("objectives", {
  # tests for the property `objectives` (array[character])
  # A program objective to search for

  # uncomment below to test the property 
  #expect_equal(model.instance$`objectives`, "EXPECTED_RESULT")
})

