# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ScalesApi")

api.instance <- ScalesApi$new()

test_that("ScalesGet", {
  # tests for ScalesGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the Scales
  # Returns a list of Scales available on a server.  An Observation Variable has 3 critical parts; A Trait being observed, a Method for making the observation, and a Scale on which the observation can be measured and compared with other observations.
  # @param scale.db.id character The unique identifier for a scale (optional)
  # @param observation.variable.db.id character The unique identifier for an observation variable (optional)
  # @param external.reference.id character An external reference ID. Could be a simple string or a URI. (use with `externalReferenceSource` parameter) (optional)
  # @param external.reference.source character An identifier for the source system or database of an external reference (use with `externalReferenceID` parameter) (optional)
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [ScaleListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ScalesPost", {
  # tests for ScalesPost
  # base path: https://test-server.brapi.org/brapi/v2
  # Add new Scales
  # Create new scale objects in the database
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param scale.base.class array[ScaleBaseClass]  (optional)
  # @return [ScaleListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ScalesScaleDbIdGet", {
  # tests for ScalesScaleDbIdGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the details of a specific Scale
  # Retrieve details about a specific scale  An Observation Variable has 3 critical parts: A Trait being observed, a Method for making the observation, and a Scale on which the observation can be measured and compared with other observations.
  # @param scale.db.id character Id of the scale to retrieve details of.
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [ScaleSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ScalesScaleDbIdPut", {
  # tests for ScalesScaleDbIdPut
  # base path: https://test-server.brapi.org/brapi/v2
  # Update an existing Scale
  # Update the details of an existing scale
  # @param scale.db.id character Id of the scale to retrieve details of.
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param body ScaleBaseClass  (optional)
  # @return [ScaleSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

