# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PersonAllOf")

model.instance <- PersonAllOf$new()

test_that("personDbId", {
  # tests for the property `personDbId` (character)
  # Unique ID for a person

  # uncomment below to test the property 
  #expect_equal(model.instance$`personDbId`, "EXPECTED_RESULT")
})

