# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Call")

model.instance <- Call$new()

test_that("additionalInfo", {
  # tests for the property `additionalInfo` (map(character))
  # Additional arbitrary info

  # uncomment below to test the property 
  #expect_equal(model.instance$`additionalInfo`, "EXPECTED_RESULT")
})

test_that("callSetDbId", {
  # tests for the property `callSetDbId` (character)
  # The ID of the call set this variant call belongs to.  If this field is not present, the ordering of the call sets from a &#x60;SearchCallSetsRequest&#x60; over this &#x60;VariantSet&#x60; is guaranteed to match the ordering of the calls on this &#x60;Variant&#x60;. The number of results will also be the same.

  # uncomment below to test the property 
  #expect_equal(model.instance$`callSetDbId`, "EXPECTED_RESULT")
})

test_that("callSetName", {
  # tests for the property `callSetName` (character)
  # The name of the call set this variant call belongs to. If this field is not present, the ordering of the call sets from a &#x60;SearchCallSetsRequest&#x60; over this &#x60;VariantSet&#x60; is guaranteed to match the ordering of the calls on this &#x60;Variant&#x60;. The number of results will also be the same.

  # uncomment below to test the property 
  #expect_equal(model.instance$`callSetName`, "EXPECTED_RESULT")
})

test_that("genotype", {
  # tests for the property `genotype` (ListValue)

  # uncomment below to test the property 
  #expect_equal(model.instance$`genotype`, "EXPECTED_RESULT")
})

test_that("genotype_likelihood", {
  # tests for the property `genotype_likelihood` (array[numeric])
  # The genotype likelihood for this variant call. Each array entry represents how likely a specific genotype is for this call as log10(P(data | genotype)), analogous to the GL tag in the VCF spec. The value ordering is defined by the GL tag in the VCF spec.

  # uncomment below to test the property 
  #expect_equal(model.instance$`genotype_likelihood`, "EXPECTED_RESULT")
})

test_that("phaseSet", {
  # tests for the property `phaseSet` (character)
  # If this field is populated, this variant call&#39;s genotype ordering implies the phase of the bases and is consistent with any other variant calls on the same contig which have the same phase set string.

  # uncomment below to test the property 
  #expect_equal(model.instance$`phaseSet`, "EXPECTED_RESULT")
})

test_that("variantDbId", {
  # tests for the property `variantDbId` (character)
  # The ID of the variant this call belongs to.

  # uncomment below to test the property 
  #expect_equal(model.instance$`variantDbId`, "EXPECTED_RESULT")
})

test_that("variantName", {
  # tests for the property `variantName` (character)
  # The name of the variant this call belongs to.

  # uncomment below to test the property 
  #expect_equal(model.instance$`variantName`, "EXPECTED_RESULT")
})

