# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GermplasmOrigin")

model.instance <- GermplasmOrigin$new()

test_that("coordinateUncertainty", {
  # tests for the property `coordinateUncertainty` (character)
  # Uncertainty associated with the coordinates in meters. Leave the value empty if the uncertainty is unknown.

  # uncomment below to test the property 
  #expect_equal(model.instance$`coordinateUncertainty`, "EXPECTED_RESULT")
})

test_that("coordinates", {
  # tests for the property `coordinates` (GeoJSON)

  # uncomment below to test the property 
  #expect_equal(model.instance$`coordinates`, "EXPECTED_RESULT")
})

