# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VendorSpecification")

model.instance <- VendorSpecification$new()

test_that("additionalInfo", {
  # tests for the property `additionalInfo` (map(object))
  # Additional arbitrary information specific to a particular Vendor. Look for the Vendors specific API documentation for more details

  # uncomment below to test the property 
  #expect_equal(model.instance$`additionalInfo`, "EXPECTED_RESULT")
})

test_that("services", {
  # tests for the property `services` (array[VendorSpecificationService])
  # List of platform specifications available at the vendor

  # uncomment below to test the property 
  #expect_equal(model.instance$`services`, "EXPECTED_RESULT")
})

test_that("vendorContact", {
  # tests for the property `vendorContact` (VendorContact)

  # uncomment below to test the property 
  #expect_equal(model.instance$`vendorContact`, "EXPECTED_RESULT")
})

