# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ScaleBaseClassValidValuesCategories")

model.instance <- ScaleBaseClassValidValuesCategories$new()

test_that("label", {
  # tests for the property `label` (character)
  # A text label for a category

  # uncomment below to test the property 
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)
  # The actual value for a category

  # uncomment below to test the property 
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

