# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MethodBaseClass")

model.instance <- MethodBaseClass$new()

test_that("additionalInfo", {
  # tests for the property `additionalInfo` (map(character))
  # Additional arbitrary info

  # uncomment below to test the property 
  #expect_equal(model.instance$`additionalInfo`, "EXPECTED_RESULT")
})

test_that("bibliographicalReference", {
  # tests for the property `bibliographicalReference` (character)
  # Bibliographical reference describing the method.  MIAPPE V1.1 (DM-91) Reference associated to the method - URI/DOI of reference describing the method.

  # uncomment below to test the property 
  #expect_equal(model.instance$`bibliographicalReference`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # Method description  MIAPPE V1.1 (DM-90) Method description - Textual description of the method, which may extend a method defined in an external reference with specific parameters, e.g. growth stage, inoculation precise organ (leaf number)

  # uncomment below to test the property 
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("externalReferences", {
  # tests for the property `externalReferences` (array[object])
  # An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.

  # uncomment below to test the property 
  #expect_equal(model.instance$`externalReferences`, "EXPECTED_RESULT")
})

test_that("formula", {
  # tests for the property `formula` (character)
  # For computational methods i.e., when the method consists in assessing the trait by computing measurements, write the generic formula used for the calculation

  # uncomment below to test the property 
  #expect_equal(model.instance$`formula`, "EXPECTED_RESULT")
})

test_that("methodClass", {
  # tests for the property `methodClass` (character)
  # Method class (examples: \&quot;Measurement\&quot;, \&quot;Counting\&quot;, \&quot;Estimation\&quot;, \&quot;Computation\&quot;, etc.)

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodClass`, "EXPECTED_RESULT")
})

test_that("methodName", {
  # tests for the property `methodName` (character)
  # Human readable name for the method  MIAPPE V1.1 (DM-88) Method  Name of the method of observation

  # uncomment below to test the property 
  #expect_equal(model.instance$`methodName`, "EXPECTED_RESULT")
})

test_that("ontologyReference", {
  # tests for the property `ontologyReference` (OntologyReference)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ontologyReference`, "EXPECTED_RESULT")
})

