# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ImagesApi")

api.instance <- ImagesApi$new()

test_that("ImagesGet", {
  # tests for ImagesGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the image meta data summaries
  # Get filtered set of image meta data  Implementation Notes  - &#39;&#39;imageURL&#39;&#39; should be a complete URL describing the location of the image. There is no BrAPI call for retrieving the image content, so it could be on a different path, or a different host.  - &#39;&#39;descriptiveOntologyTerm&#39;&#39; can be thought of as Tags for the image. These could be simple descriptive words, or ontology references, or full ontology URI&#39;&#39;s.
  # @param image.db.id character The unique identifier for a image (optional)
  # @param image.name character The human readable name of an image (optional)
  # @param observation.unit.db.id character The unique identifier of the observation unit an image is portraying (optional)
  # @param observation.db.id character The unique identifier of the observation an image is associated with (optional)
  # @param descriptive.ontology.term character A descriptive term associated with an image (optional)
  # @param external.reference.id character An external reference ID. Could be a simple string or a URI. (use with `externalReferenceSource` parameter) (optional)
  # @param external.reference.source character An identifier for the source system or database of an external reference (use with `externalReferenceID` parameter) (optional)
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [ImageListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ImagesImageDbIdGet", {
  # tests for ImagesImageDbIdGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the an image meta data summary
  # Get one image meta data object  Implementation Notes  - &#39;&#39;imageURL&#39;&#39; should be a complete URL describing the location of the image. There is no BrAPI call for retrieving the image content, so it could be on a different path, or a different host.  - &#39;&#39;descriptiveOntologyTerm&#39;&#39; can be thought of as Tags for the image. These could be simple descriptive words, or ontology references, or full ontology URI&#39;&#39;s.
  # @param image.db.id character The unique identifier for a image
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [ImageSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ImagesImageDbIdImagecontentPut", {
  # tests for ImagesImageDbIdImagecontentPut
  # base path: https://test-server.brapi.org/brapi/v2
  # Update an image with the image file content
  # Update an image with the image file content  Implementation Notes  - This call should be paired with &#39;PUT /images/{imageDbId}&#39; for full capability  - A server may choose to modify the image meta data object based on the actually image which has been uploaded.   - Image data may be stored in a database or file system. Servers should generate and provide the \&quot;imageURL\&quot; for retrieving the image, wherever it happens to live.
  # @param image.db.id character The unique identifier for a image
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param body data.frame  (optional)
  # @return [ImageSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ImagesImageDbIdPut", {
  # tests for ImagesImageDbIdPut
  # base path: https://test-server.brapi.org/brapi/v2
  # Update an image meta data
  # Update an image meta data object  Implementation Notes  - This call should be paired with &#39;PUT /images/{imageDbId}/imagecontent&#39; for full capability  - A server may choose to modify the image meta data object based on the actually image which has been uploaded.   - Image data may be stored in a database or file system. Servers should generate and provide the \&quot;imageURL\&quot; as an absolute path for retrieving the image, wherever it happens to live.   - &#39;descriptiveOntologyTerm&#39; can be thought of as Tags for the image. These could be simple descriptive words, or ontology references, or full ontology URI&#39;s.   - The &#39;/images&#39; calls support a GeoJSON object structure for describing their location. The BrAPI spec for GeoJSON only supports two of the possible geometries: Points and Polygons.   - With most images, the Point geometry should be used, and it should indicate the longitude and latitude of the camera.   - For top down images (ie from drones, cranes, etc), the Point geometry may be used to indicate the longitude and latitude of the centroid of the image content, and the Polygon geometry may be used to indicate the border of the image content.
  # @param image.db.id character The unique identifier for a image
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param image.new.request ImageNewRequest  (optional)
  # @return [ImageSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ImagesPost", {
  # tests for ImagesPost
  # base path: https://test-server.brapi.org/brapi/v2
  # Create new image meta data objects
  # Create new image meta data objects  Implementation Notes  - &#39;&#39;imageURL&#39;&#39; should be a complete URL describing the location of the image. There is no BrAPI call for retrieving the image content, so it could be on a different path, or a different host.  - &#39;&#39;descriptiveOntologyTerm&#39;&#39; can be thought of as Tags for the image. These could be simple descriptive words, or ontology references, or full ontology URI&#39;&#39;s.  - The &#39;/images&#39; calls support a GeoJSON object structure for describing their location. The BrAPI spec for GeoJSON only supports two of the possible geometries: Points and Polygons.  - With most images, the Point geometry should be used, and it should indicate the longitude and latitude of the camera.  - For top down images (ie from drones, cranes, etc), the Point geometry may be used to indicate the longitude and latitude of the centroid of the image content, and the Polygon geometry may be used to indicate the border of the image content. &#39;
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param image.new.request array[ImageNewRequest]  (optional)
  # @return [ImageListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchImagesPost", {
  # tests for SearchImagesPost
  # base path: https://test-server.brapi.org/brapi/v2
  # Submit a search request for Images
  # Get filtered set of image meta data  Implementation Notes  - &#39;&#39;imageURL&#39;&#39; should be a complete URL describing the location of the image. There is no BrAPI call for retrieving the image content, so it could be on a different path, or a different host.  - &#39;descriptiveOntologyTerm&#39; can be thought of as Tags for the image. These could be simple descriptive words, or ontology references, or full ontology URI&#39;s.  See Search Services for additional implementation details.
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param image.search.request ImageSearchRequest  (optional)
  # @return [ImageListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchImagesSearchResultsDbIdGet", {
  # tests for SearchImagesSearchResultsDbIdGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the results of an Images search request
  # Get filtered set of image meta data  Implementation Notes  - &#39;&#39;imageURL&#39;&#39; should be a complete URL describing the location of the image. There is no BrAPI call for retrieving the image content, so it could be on a different path, or a different host.  - &#39;&#39;descriptiveOntologyTerm&#39;&#39; can be thought of as Tags for the image. These could be simple descriptive words, or ontology references, or full ontology URI&#39;&#39;s.
  # @param search.results.db.id character Unique identifier which references the search results
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [ImageListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

