# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DataFile")

model.instance <- DataFile$new()

test_that("fileDescription", {
  # tests for the property `fileDescription` (character)
  # A human readable description of the file contents

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileDescription`, "EXPECTED_RESULT")
})

test_that("fileMD5Hash", {
  # tests for the property `fileMD5Hash` (character)
  # The MD5 Hash of the file contents to be used as a check sum

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileMD5Hash`, "EXPECTED_RESULT")
})

test_that("fileName", {
  # tests for the property `fileName` (character)
  # The name of the file

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileName`, "EXPECTED_RESULT")
})

test_that("fileSize", {
  # tests for the property `fileSize` (integer)
  # The size of the file in bytes

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileSize`, "EXPECTED_RESULT")
})

test_that("fileType", {
  # tests for the property `fileType` (character)
  # The type or format of the file. Preferably MIME Type.

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileType`, "EXPECTED_RESULT")
})

test_that("fileURL", {
  # tests for the property `fileURL` (character)
  # The absolute URL where the file is located

  # uncomment below to test the property 
  #expect_equal(model.instance$`fileURL`, "EXPECTED_RESULT")
})

