# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GermplasmSearchRequestAllOf")

model.instance <- GermplasmSearchRequestAllOf$new()

test_that("accessionNumbers", {
  # tests for the property `accessionNumbers` (array[character])
  # List unique identifiers for accessions within a genebank

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessionNumbers`, "EXPECTED_RESULT")
})

test_that("collections", {
  # tests for the property `collections` (array[character])
  # A specific panel/collection/population name this germplasm belongs to.

  # uncomment below to test the property 
  #expect_equal(model.instance$`collections`, "EXPECTED_RESULT")
})

test_that("genus", {
  # tests for the property `genus` (array[character])
  # List of Genus names to identify germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`genus`, "EXPECTED_RESULT")
})

test_that("germplasmPUIs", {
  # tests for the property `germplasmPUIs` (array[character])
  # List of Permanent Unique Identifiers to identify germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`germplasmPUIs`, "EXPECTED_RESULT")
})

test_that("parentDbIds", {
  # tests for the property `parentDbIds` (array[character])
  # Search for Germplasm with these parents

  # uncomment below to test the property 
  #expect_equal(model.instance$`parentDbIds`, "EXPECTED_RESULT")
})

test_that("progenyDbIds", {
  # tests for the property `progenyDbIds` (array[character])
  # Search for Germplasm with these children

  # uncomment below to test the property 
  #expect_equal(model.instance$`progenyDbIds`, "EXPECTED_RESULT")
})

test_that("species", {
  # tests for the property `species` (array[character])
  # List of Species names to identify germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`species`, "EXPECTED_RESULT")
})

test_that("synonyms", {
  # tests for the property `synonyms` (array[character])
  # List of alternative names or IDs used to reference this germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`synonyms`, "EXPECTED_RESULT")
})

