# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VendorPlateSubmissionId")

model.instance <- VendorPlateSubmissionId$new()

test_that("submissionId", {
  # tests for the property `submissionId` (character)
  # A unique, alpha-numeric ID which identifies a set of plates which have been successfully submitted.

  # uncomment below to test the property 
  #expect_equal(model.instance$`submissionId`, "EXPECTED_RESULT")
})

