# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ScaleBaseClassValidValues")

model.instance <- ScaleBaseClassValidValues$new()

test_that("categories", {
  # tests for the property `categories` (array[ScaleBaseClassValidValuesCategories])
  # List of possible values with optional labels

  # uncomment below to test the property 
  #expect_equal(model.instance$`categories`, "EXPECTED_RESULT")
})

test_that("max", {
  # tests for the property `max` (integer)
  # Maximum value (used for field data capture control).

  # uncomment below to test the property 
  #expect_equal(model.instance$`max`, "EXPECTED_RESULT")
})

test_that("min", {
  # tests for the property `min` (integer)
  # Minimum value (used for data capture control) for numerical and date scales

  # uncomment below to test the property 
  #expect_equal(model.instance$`min`, "EXPECTED_RESULT")
})

