# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SampleAllOf")

model.instance <- SampleAllOf$new()

test_that("sampleDbId", {
  # tests for the property `sampleDbId` (character)
  # The ID which uniquely identifies a sample  MIAPPE V1.1 (DM-76) Sample ID - Unique identifier for the sample.

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleDbId`, "EXPECTED_RESULT")
})

