# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SampleNewRequest")

model.instance <- SampleNewRequest$new()

test_that("additionalInfo", {
  # tests for the property `additionalInfo` (map(character))
  # Additional arbitrary info

  # uncomment below to test the property 
  #expect_equal(model.instance$`additionalInfo`, "EXPECTED_RESULT")
})

test_that("column", {
  # tests for the property `column` (integer)
  # The Column identifier for this samples location in the plate

  # uncomment below to test the property 
  #expect_equal(model.instance$`column`, "EXPECTED_RESULT")
})

test_that("externalReferences", {
  # tests for the property `externalReferences` (array[object])
  # An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.

  # uncomment below to test the property 
  #expect_equal(model.instance$`externalReferences`, "EXPECTED_RESULT")
})

test_that("germplasmDbId", {
  # tests for the property `germplasmDbId` (character)
  # The ID which uniquely identifies a germplasm

  # uncomment below to test the property 
  #expect_equal(model.instance$`germplasmDbId`, "EXPECTED_RESULT")
})

test_that("observationUnitDbId", {
  # tests for the property `observationUnitDbId` (character)
  # The ID which uniquely identifies an observation unit

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationUnitDbId`, "EXPECTED_RESULT")
})

test_that("plateDbId", {
  # tests for the property `plateDbId` (character)
  # The ID which uniquely identifies a plate of samples

  # uncomment below to test the property 
  #expect_equal(model.instance$`plateDbId`, "EXPECTED_RESULT")
})

test_that("plateName", {
  # tests for the property `plateName` (character)
  # The human readable name of a plate

  # uncomment below to test the property 
  #expect_equal(model.instance$`plateName`, "EXPECTED_RESULT")
})

test_that("programDbId", {
  # tests for the property `programDbId` (character)
  # The ID which uniquely identifies a program within the given database server

  # uncomment below to test the property 
  #expect_equal(model.instance$`programDbId`, "EXPECTED_RESULT")
})

test_that("row", {
  # tests for the property `row` (character)
  # The Row identifier for this samples location in the plate

  # uncomment below to test the property 
  #expect_equal(model.instance$`row`, "EXPECTED_RESULT")
})

test_that("sampleBarcode", {
  # tests for the property `sampleBarcode` (character)
  # A unique identifier physically attached to the sample

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleBarcode`, "EXPECTED_RESULT")
})

test_that("sampleDescription", {
  # tests for the property `sampleDescription` (character)
  # Description of a sample  MIAPPE V1.1 (DM-79) Sample description - Any information not captured by the other sample fields, including quantification, sample treatments and processing.

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleDescription`, "EXPECTED_RESULT")
})

test_that("sampleGroupDbId", {
  # tests for the property `sampleGroupDbId` (character)
  # The ID which uniquely identifies a group of samples

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleGroupDbId`, "EXPECTED_RESULT")
})

test_that("sampleName", {
  # tests for the property `sampleName` (character)
  # The name of the sample

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleName`, "EXPECTED_RESULT")
})

test_that("samplePUI", {
  # tests for the property `samplePUI` (character)
  # A permanent unique identifier for the sample (DOI, URL, UUID, etc)  MIAPPE V1.1 (DM-81) External ID - An identifier for the sample in a persistent repository, comprising the name of the repository and the accession number of the observation unit therein. Submission to the EBI Biosamples repository is recommended. URI are recommended when possible. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`samplePUI`, "EXPECTED_RESULT")
})

test_that("sampleTimestamp", {
  # tests for the property `sampleTimestamp` (character)
  # The date and time a sample was collected from the field  MIAPPE V1.1 (DM-80) Collection date - The date and time when the sample was collected / harvested

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleTimestamp`, "EXPECTED_RESULT")
})

test_that("sampleType", {
  # tests for the property `sampleType` (character)
  # The type of sample taken. ex. &#39;DNA&#39;, &#39;RNA&#39;, &#39;Tissue&#39;, etc

  # uncomment below to test the property 
  #expect_equal(model.instance$`sampleType`, "EXPECTED_RESULT")
})

test_that("studyDbId", {
  # tests for the property `studyDbId` (character)
  # The ID which uniquely identifies a study within the given database server

  # uncomment below to test the property 
  #expect_equal(model.instance$`studyDbId`, "EXPECTED_RESULT")
})

test_that("takenBy", {
  # tests for the property `takenBy` (character)
  # The name or identifier of the entity which took the sample from the field

  # uncomment below to test the property 
  #expect_equal(model.instance$`takenBy`, "EXPECTED_RESULT")
})

test_that("tissueType", {
  # tests for the property `tissueType` (character)
  # The type of tissue sampled. ex. &#39;Leaf&#39;, &#39;Root&#39;, etc.  MIAPPE V1.1 (DM-78) Plant anatomical entity - A description of  the plant part (e.g. leaf) or the plant product (e.g. resin) from which the sample was taken, in the form of an accession number to a suitable controlled vocabulary (Plant Ontology).

  # uncomment below to test the property 
  #expect_equal(model.instance$`tissueType`, "EXPECTED_RESULT")
})

test_that("trialDbId", {
  # tests for the property `trialDbId` (character)
  # The ID which uniquely identifies a trial within the given database server

  # uncomment below to test the property 
  #expect_equal(model.instance$`trialDbId`, "EXPECTED_RESULT")
})

test_that("well", {
  # tests for the property `well` (character)
  # The Well identifier for this samples location in the plate. Usually a concatenation of Row and Column, or just a number if the samples are not part of an ordered plate.

  # uncomment below to test the property 
  #expect_equal(model.instance$`well`, "EXPECTED_RESULT")
})

