# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ObservationVariable")

model.instance <- ObservationVariable$new()

test_that("additionalInfo", {
  # tests for the property `additionalInfo` (map(character))
  # Additional arbitrary info

  # uncomment below to test the property 
  #expect_equal(model.instance$`additionalInfo`, "EXPECTED_RESULT")
})

test_that("commonCropName", {
  # tests for the property `commonCropName` (character)
  # Crop name (examples: \&quot;Maize\&quot;, \&quot;Wheat\&quot;)

  # uncomment below to test the property 
  #expect_equal(model.instance$`commonCropName`, "EXPECTED_RESULT")
})

test_that("contextOfUse", {
  # tests for the property `contextOfUse` (array[character])
  # Indication of how trait is routinely used. (examples: [\&quot;Trial evaluation\&quot;, \&quot;Nursery evaluation\&quot;])

  # uncomment below to test the property 
  #expect_equal(model.instance$`contextOfUse`, "EXPECTED_RESULT")
})

test_that("defaultValue", {
  # tests for the property `defaultValue` (character)
  # Variable default value. (examples: \&quot;red\&quot;, \&quot;2.3\&quot;, etc.)

  # uncomment below to test the property 
  #expect_equal(model.instance$`defaultValue`, "EXPECTED_RESULT")
})

test_that("documentationURL", {
  # tests for the property `documentationURL` (character)
  # A URL to the human readable documentation of this object

  # uncomment below to test the property 
  #expect_equal(model.instance$`documentationURL`, "EXPECTED_RESULT")
})

test_that("externalReferences", {
  # tests for the property `externalReferences` (array[object])
  # An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.

  # uncomment below to test the property 
  #expect_equal(model.instance$`externalReferences`, "EXPECTED_RESULT")
})

test_that("growthStage", {
  # tests for the property `growthStage` (character)
  # Growth stage at which measurement is made (examples: \&quot;flowering\&quot;)

  # uncomment below to test the property 
  #expect_equal(model.instance$`growthStage`, "EXPECTED_RESULT")
})

test_that("institution", {
  # tests for the property `institution` (character)
  # Name of institution submitting the variable

  # uncomment below to test the property 
  #expect_equal(model.instance$`institution`, "EXPECTED_RESULT")
})

test_that("language", {
  # tests for the property `language` (character)
  # 2 letter ISO 639-1 code for the language of submission of the variable.

  # uncomment below to test the property 
  #expect_equal(model.instance$`language`, "EXPECTED_RESULT")
})

test_that("method", {
  # tests for the property `method` (MethodBaseClass)

  # uncomment below to test the property 
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})

test_that("ontologyReference", {
  # tests for the property `ontologyReference` (OntologyReference)

  # uncomment below to test the property 
  #expect_equal(model.instance$`ontologyReference`, "EXPECTED_RESULT")
})

test_that("scale", {
  # tests for the property `scale` (ScaleBaseClass)

  # uncomment below to test the property 
  #expect_equal(model.instance$`scale`, "EXPECTED_RESULT")
})

test_that("scientist", {
  # tests for the property `scientist` (character)
  # Name of scientist submitting the variable.

  # uncomment below to test the property 
  #expect_equal(model.instance$`scientist`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)
  # Variable status. (examples: \&quot;recommended\&quot;, \&quot;obsolete\&quot;, \&quot;legacy\&quot;, etc.)

  # uncomment below to test the property 
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("submissionTimestamp", {
  # tests for the property `submissionTimestamp` (character)
  # Timestamp when the Variable was added (ISO 8601)

  # uncomment below to test the property 
  #expect_equal(model.instance$`submissionTimestamp`, "EXPECTED_RESULT")
})

test_that("synonyms", {
  # tests for the property `synonyms` (array[character])
  # Other variable names

  # uncomment below to test the property 
  #expect_equal(model.instance$`synonyms`, "EXPECTED_RESULT")
})

test_that("trait", {
  # tests for the property `trait` (TraitBaseClass)

  # uncomment below to test the property 
  #expect_equal(model.instance$`trait`, "EXPECTED_RESULT")
})

test_that("observationVariableDbId", {
  # tests for the property `observationVariableDbId` (character)
  # Variable unique identifier  MIAPPE V1.1 (DM-83) Variable ID - Code used to identify the variable in the data file. We recommend using a variable definition from the Crop Ontology where possible. Otherwise, the Crop Ontology naming convention is recommended: &lt;trait abbreviation&gt;_&lt;method abbreviation&gt;_&lt;scale abbreviation&gt;). A variable ID must be unique within a given investigation.

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationVariableDbId`, "EXPECTED_RESULT")
})

test_that("observationVariableName", {
  # tests for the property `observationVariableName` (character)
  # Variable name (usually a short name)  MIAPPE V1.1 (DM-84) Variable name - Name of the variable.

  # uncomment below to test the property 
  #expect_equal(model.instance$`observationVariableName`, "EXPECTED_RESULT")
})

