# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GermplasmAttributesApi")

api.instance <- GermplasmAttributesApi$new()

test_that("AttributesAttributeDbIdGet", {
  # tests for AttributesAttributeDbIdGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the details for a specific Germplasm Attribute
  # Get the details for a specific Germplasm Attribute
  # @param attribute.db.id character The unique id for an attribute
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [GermplasmAttributeSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AttributesAttributeDbIdPut", {
  # tests for AttributesAttributeDbIdPut
  # base path: https://test-server.brapi.org/brapi/v2
  # Update an existing Germplasm Attribute
  # Update an existing Germplasm Attribute
  # @param attribute.db.id character The unique id for an attribute
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param germplasm.attribute.new.request GermplasmAttributeNewRequest  (optional)
  # @return [GermplasmAttributeSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AttributesCategoriesGet", {
  # tests for AttributesCategoriesGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the Categories of Germplasm Attributes
  # List all available attribute categories.
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [GermplasmAttributeCategoryListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AttributesGet", {
  # tests for AttributesGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the Germplasm Attributes
  # List available attributes.
  # @param attribute.category character The general category for the attribute. very similar to Trait class. (optional)
  # @param attribute.db.id character The unique id for an attribute (optional)
  # @param attribute.name character The human readable name for an attribute (optional)
  # @param germplasm.db.id character Get all attributes associated with this germplasm (optional)
  # @param external.reference.id character An external reference ID. Could be a simple string or a URI. (use with `externalReferenceSource` parameter) (optional)
  # @param external.reference.source character An identifier for the source system or database of an external reference (use with `externalReferenceID` parameter) (optional)
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [GermplasmAttributeListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AttributesPost", {
  # tests for AttributesPost
  # base path: https://test-server.brapi.org/brapi/v2
  # Create new Germplasm Attributes
  # Create new Germplasm Attributes
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param germplasm.attribute.new.request array[GermplasmAttributeNewRequest]  (optional)
  # @return [GermplasmAttributeListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchAttributesPost", {
  # tests for SearchAttributesPost
  # base path: https://test-server.brapi.org/brapi/v2
  # Submit a search request for Germplasm Attributes
  # Search for a set of Germplasm Attributes based on some criteria          See Search Services for additional implementation details.
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param germplasm.attribute.search.request GermplasmAttributeSearchRequest  (optional)
  # @return [GermplasmAttributeListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("SearchAttributesSearchResultsDbIdGet", {
  # tests for SearchAttributesSearchResultsDbIdGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the results of a Germplasm Attributes search request
  # Get the results of a Germplasm Attributes search request  See Search Services for additional implementation details.
  # @param search.results.db.id character Unique identifier which references the search results
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [GermplasmAttributeListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

