# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test GermplasmAllOf")

model.instance <- GermplasmAllOf$new()

test_that("germplasmDbId", {
  # tests for the property `germplasmDbId` (character)
  # The ID which uniquely identifies a germplasm within the given database server  MIAPPE V1.1 (DM-41) Biological material ID - Code used to identify the biological material in the data file. Should be unique within the Investigation. Can correspond to experimental plant ID, seed lot ID, etc. This material identification is different from a BiosampleID which corresponds to Observation Unit or Samples sections below.

  # uncomment below to test the property 
  #expect_equal(model.instance$`germplasmDbId`, "EXPECTED_RESULT")
})

