# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VariantsSearchRequestAllOf")

model.instance <- VariantsSearchRequestAllOf$new()

test_that("callSetDbIds", {
  # tests for the property `callSetDbIds` (array[character])
  # Only return variant calls which belong to call sets with these IDs. If unspecified, return all variants and no variant call objects.

  # uncomment below to test the property 
  #expect_equal(model.instance$`callSetDbIds`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (integer)
  # The end of the window (0-based, exclusive) for which overlapping variants should be returned.

  # uncomment below to test the property 
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("referenceDbId", {
  # tests for the property `referenceDbId` (character)
  # Only return variants on this reference.

  # uncomment below to test the property 
  #expect_equal(model.instance$`referenceDbId`, "EXPECTED_RESULT")
})

test_that("start", {
  # tests for the property `start` (integer)
  # The beginning of the window (0-based, inclusive) for which overlapping variants should be returned. Genomic positions are non-negative integers less than reference length. Requests spanning the join of circular genomes are represented as two requests one on each side of the join (position 0).

  # uncomment below to test the property 
  #expect_equal(model.instance$`start`, "EXPECTED_RESULT")
})

test_that("variantDbIds", {
  # tests for the property `variantDbIds` (array[character])
  # The &#x60;Variant&#x60;s to search.

  # uncomment below to test the property 
  #expect_equal(model.instance$`variantDbIds`, "EXPECTED_RESULT")
})

test_that("variantSetDbIds", {
  # tests for the property `variantSetDbIds` (array[character])
  # The &#x60;VariantSet&#x60; to search.

  # uncomment below to test the property 
  #expect_equal(model.instance$`variantSetDbIds`, "EXPECTED_RESULT")
})

