# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test MethodsApi")

api.instance <- MethodsApi$new()

test_that("MethodsGet", {
  # tests for MethodsGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the Methods
  # Returns a list of Methods available on a server.  An Observation Variable has 3 critical parts; A Trait being observed, a Method for making the observation, and a Scale on which the observation can be measured and compared with other observations.&#39;
  # @param method.db.id character The unique identifier for a method (optional)
  # @param observation.variable.db.id character The unique identifier for an observation variable (optional)
  # @param external.reference.id character An external reference ID. Could be a simple string or a URI. (use with `externalReferenceSource` parameter) (optional)
  # @param external.reference.source character An identifier for the source system or database of an external reference (use with `externalReferenceID` parameter) (optional)
  # @param page integer Used to request a specific page of data to be returned.  The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`. (optional)
  # @param page.size integer The size of the pages to be returned. Default is `1000`. (optional)
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [MethodListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MethodsMethodDbIdGet", {
  # tests for MethodsMethodDbIdGet
  # base path: https://test-server.brapi.org/brapi/v2
  # Get the details for a specific Method
  # Retrieve details about a specific method  An Observation Variable has 3 critical parts; A Trait being observed, a Method for making the observation, and a Scale on which the observation can be measured and compared with other observations.
  # @param method.db.id character Id of the method to retrieve details of.
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @return [MethodSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MethodsMethodDbIdPut", {
  # tests for MethodsMethodDbIdPut
  # base path: https://test-server.brapi.org/brapi/v2
  # Update an existing Method
  # Update the details of an existing method
  # @param method.db.id character Id of the method to retrieve details of.
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param body MethodBaseClass  (optional)
  # @return [MethodSingleResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("MethodsPost", {
  # tests for MethodsPost
  # base path: https://test-server.brapi.org/brapi/v2
  # Add new Methods
  # Create new method objects in the database
  # @param authorization character HTTP HEADER - Token used for Authorization   <strong> Bearer {token_string} </strong> (optional)
  # @param method.base.class array[MethodBaseClass]  (optional)
  # @return [MethodListResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

